# Generated by Django 4.2.26 on 2025-11-27 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingSystemVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=255)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('affiliate_link', models.URLField(blank=True, help_text='The specific URL with TerraLux tracking parameters.', max_length=500, null=True)),
                ('is_certified', models.BooleanField(default=False, help_text="If TRUE, displays 'Certified Partner' badge.")),
                ('consultation_enabled', models.BooleanField(default=False, help_text="If TRUE, shows the 'Schedule Consultation' button.")),
                ('coordinates', models.CharField(blank=True, help_text='Lat,Lng format', max_length=100)),
                ('primary_category', models.CharField(choices=[('PREFAB', 'Prefab & Modular'), ('NATURAL', 'Natural & Earthen'), ('DOMES', 'Domes & Shells'), ('3D_PRINT', '3D Printed'), ('TREE', 'Tree Homes'), ('HEALTHY', 'Healthy Systems'), ('COMMUNITY', 'Community')], max_length=50)),
                ('heal_alignment', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('CORE_COUNCIL', 'Core Council'), ('PRIORITY', 'Priority Prospect'), ('ACTIVE', 'Active Vendor')], default='ACTIVE', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('contact_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed product description')),
                ('price_range', models.CharField(blank=True, help_text="e.g., '$50k-$100k'", max_length=100)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Technical specifications')),
                ('images', models.JSONField(blank=True, default=list, help_text='List of image URLs')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight this model')),
                ('glb_file', models.FileField(blank=True, null=True, upload_to='models_3d/')),
                ('relationship_type', models.CharField(default='Manufacturer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vendors.buildingsystemvendor')),
            ],
            options={
                'verbose_name': 'Building Model',
                'verbose_name_plural': 'Building Models',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='vendors.modelvendor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='vendors.buildingsystemvendor')),
            ],
            options={
                'verbose_name': 'Consultation Request',
                'verbose_name_plural': 'Consultation Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AffiliateClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('converted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='vendors.buildingsystemvendor')),
            ],
        ),
    ]
